sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - EXECUTE_CS_CHECK=true
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - composer test
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi

notifications:
  email: true
